import 'dart:math';

/// Generates cryptographically random identifiers, sharing one secure-random byte source: RFC
/// 4122 version-4 UUIDs for installation client IDs, and 32-character hexadecimal IDs for
/// session-unique request message IDs.
class RandomIdGenerator {
  /// Creates a generator backed by the platform's secure random source.
  RandomIdGenerator();

  /// The secure random source used for generated bytes.
  final Random _random = Random.secure();

  /// Generates one lowercase RFC 4122 version-4 UUID.
  String generateUuid() {
    final List<int> bytes = _randomBytes();
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    final String hex = _hex(bytes);
    return '${hex.substring(0, 8)}-${hex.substring(8, 12)}-'
        '${hex.substring(12, 16)}-${hex.substring(16, 20)}-'
        '${hex.substring(20, 32)}';
  }

  /// Generates a 32-character lowercase hexadecimal message ID.
  String generateMessageId() => _hex(_randomBytes());

  /// Generates 16 cryptographically random bytes.
  List<int> _randomBytes() =>
      List<int>.generate(16, (_) => _random.nextInt(256));

  /// Encodes [bytes] as lowercase hexadecimal.
  String _hex(List<int> bytes) =>
      bytes.map((int byte) => byte.toRadixString(16).padLeft(2, '0')).join();
}
