include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    missing_required_param: error

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    always_declare_return_types: true
    prefer_single_quotes: true
    require_trailing_commas: true
    prefer_initializing_formals: false
