#pragma once

#include "ipc/ipc_constants.hpp"

#include <array>
#include <cstddef>
#include <cstdint>
#include <vector>

namespace dovahlink::adapter::ipc {

///  Sent by the connecting adapter to establish the private channel: the
///  adapter's own instance identity and a bounded peer-ownership proof token.
///  The proof's expected value and comparison policy belong to the host channel
///  that consumes this message, not to this wire contract. Also carries the
///  fields that let the host prove it holds the shared secret back, and that
///  scope the handshake to the intended Skyrim lifetime -- accepting a
///  connection is not itself proof that the responder is the legitimate host.
struct IpcHelloMessage {
  ///  Pairs this request with its `IpcHelloAckMessage` response.
  std::uint64_t correlationId = 0;
  ///  The connecting adapter's instance identity, as 16 opaque bytes.
  std::array<std::byte, 16> adapterInstanceId{};
  ///  The bounded peer-ownership proof, at most `kMaxIpcPeerProofTokenBytes`
  ///  bytes.
  std::vector<std::byte> peerProofToken;
  ///  A fresh random value generated by the adapter for every Hello it sends
  ///  -- including every retry -- and bound into the host's `hostProof` to
  ///  defeat replay.
  std::array<std::byte, kIpcChallengeBytes> challenge{};
  ///  The owning Skyrim process's lifetime identity (process id and creation
  ///  timestamp), scoping this handshake to the intended Skyrim lifetime. Not
  ///  itself a cryptographic ownership proof: it is not secret, and only
  ///  prevents two concurrently running Skyrim lifetimes from colliding over
  ///  the same discovery data -- the host's `hostProof` is what proves
  ///  ownership.
  std::array<std::byte, kIpcOwnerLifetimeIdBytes> ownerLifetimeId{};

  ///  Structural equality over every field.
  bool operator==(const IpcHelloMessage &) const = default;
};

} //  namespace dovahlink::adapter::ipc
