using DovahLink.Host.Identity;

namespace DovahLink.Host.Adapter.Ipc;

/// <summary>
/// Sent by the connecting adapter to establish the private channel: the adapter's own instance
/// identity and a bounded peer-ownership proof token. The proof's expected value and comparison
/// policy belong to the host channel that consumes this message, not to this wire contract. Also
/// carries the fields that let the host prove it holds the shared secret back, and that scope the
/// handshake to the intended Skyrim lifetime -- accepting a connection is not itself proof that the
/// responder is the legitimate host.
/// </summary>
/// The correlation id pairs this request with its <see cref="IpcHelloAckMessage"/> response.
public sealed record IpcHelloMessage : IpcMessage
{
    /// <summary>The connecting adapter's instance identity.</summary>
    public AdapterInstanceId AdapterInstanceId { get; }

    /// <summary>The owned bounded peer-ownership proof bytes.</summary>
    private readonly byte[] peerProofToken;

    /// <summary>A fresh copy of the bounded peer-ownership proof, safe for the caller to mutate.</summary>
    public byte[] PeerProofToken => peerProofToken.ToArray();

    /// <summary>
    /// The owned fresh random challenge bytes generated by the adapter for this Hello, bound into
    /// the host's <see cref="IpcHelloAckMessage.HostProof"/> to defeat replay.
    /// </summary>
    private readonly byte[] challenge;

    /// <summary>A fresh copy of this Hello's challenge bytes, safe for the caller to mutate.</summary>
    public byte[] Challenge => challenge.ToArray();

    /// <summary>
    /// The owned owning-Skyrim-process lifetime identity bytes (process id and creation timestamp),
    /// scoping this handshake to the intended Skyrim lifetime. Not itself a cryptographic ownership
    /// proof: it is not secret, and only prevents two concurrently running Skyrim lifetimes from
    /// colliding over the same discovery data -- the host's <see cref="IpcHelloAckMessage.HostProof"/>
    /// is what proves ownership.
    /// </summary>
    private readonly byte[] ownerLifetimeId;

    /// <summary>A fresh copy of this Hello's owner-lifetime-id bytes, safe for the caller to mutate.</summary>
    public byte[] OwnerLifetimeId => ownerLifetimeId.ToArray();

    /// <summary>Creates a Hello message and copies the caller's proof token into owned storage.</summary>
    /// <param name="correlationId">Pairs this request with its response.</param>
    /// <param name="adapterInstanceId">The connecting adapter's instance identity.</param>
    /// <param name="peerProofToken">The bounded peer-ownership proof to copy.</param>
    /// <param name="challenge">
    /// The fresh random challenge to copy, exactly <see cref="Constants.IpcChallengeBytes"/> bytes, or
    /// <see langword="null"/> for an all-zero placeholder (never a real value for a Hello an adapter
    /// actually sends; the adapter always supplies a real challenge).
    /// </param>
    /// <param name="ownerLifetimeId">
    /// The owning Skyrim process's lifetime identity to copy, exactly
    /// <see cref="Constants.IpcOwnerLifetimeIdBytes"/> bytes, or <see langword="null"/> for an
    /// all-zero placeholder.
    /// </param>
    public IpcHelloMessage(
        ulong correlationId,
        AdapterInstanceId adapterInstanceId,
        byte[] peerProofToken,
        byte[]? challenge = null,
        byte[]? ownerLifetimeId = null)
        : base(correlationId)
    {
        ArgumentNullException.ThrowIfNull(peerProofToken);
        if (challenge is not null && challenge.Length != Constants.IpcChallengeBytes)
        {
            throw new ArgumentException($"The challenge must be exactly {Constants.IpcChallengeBytes} bytes.", nameof(challenge));
        }

        if (ownerLifetimeId is not null && ownerLifetimeId.Length != Constants.IpcOwnerLifetimeIdBytes)
        {
            throw new ArgumentException(
                $"The owner lifetime id must be exactly {Constants.IpcOwnerLifetimeIdBytes} bytes.", nameof(ownerLifetimeId));
        }

        AdapterInstanceId = adapterInstanceId;
        this.peerProofToken = peerProofToken.ToArray();
        this.challenge = challenge?.ToArray() ?? new byte[Constants.IpcChallengeBytes];
        this.ownerLifetimeId = ownerLifetimeId?.ToArray() ?? new byte[Constants.IpcOwnerLifetimeIdBytes];
    }
}
